apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx
spec:
  description: Profile for deploying local nginx chart
  version: v0.0.2
  artifacts:
    - name: nginx-server
      path: nginx/chart
      kind: HelmChart
