apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: testing
spec:
  interval: 5m
  chart:
    spec:
      chart: dokuwiki
      version: ">=11.1.6 <12.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: testing
      interval: 30m
